# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeWorkspace < Formula
  desc "Platform engineering kit for deploying Claude Code AI agents"
  homepage "https://github.com/lamchakchan/claude-workspace"
  version "0.24.2-alpha.3.cf46d9c"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lamchakchan/claude-workspace/releases/download/v0.24.2-alpha.3.cf46d9c/claude-workspace_0.24.2-alpha.3.cf46d9c_darwin_amd64.tar.gz"
      sha256 "18900a7811cce6646500ac6a3403e8732ddab32a5951b5a87363c48048920c43"

      define_method(:install) do
        bin.install "claude-workspace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lamchakchan/claude-workspace/releases/download/v0.24.2-alpha.3.cf46d9c/claude-workspace_0.24.2-alpha.3.cf46d9c_darwin_arm64.tar.gz"
      sha256 "a651534520f657264bc832513b3d3fa4dde102ff15c86f58eae9c3442347cfdb"

      define_method(:install) do
        bin.install "claude-workspace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lamchakchan/claude-workspace/releases/download/v0.24.2-alpha.3.cf46d9c/claude-workspace_0.24.2-alpha.3.cf46d9c_linux_amd64.tar.gz"
      sha256 "c529dcde5e27cbfb9df7fd2ac47bed9fcb34e23159d6c996b578ca1b6d8b27f5"
      define_method(:install) do
        bin.install "claude-workspace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lamchakchan/claude-workspace/releases/download/v0.24.2-alpha.3.cf46d9c/claude-workspace_0.24.2-alpha.3.cf46d9c_linux_arm64.tar.gz"
      sha256 "efba95f57262f3d18f6544cab4211672a04734fac3e2eebdf3b2c1d7a119463e"
      define_method(:install) do
        bin.install "claude-workspace"
      end
    end
  end

  test do
    system "#{bin}/claude-workspace", "version"
  end
end
